version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  deploy-web:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: |
            {
              echo "REACT_APP_AWS_KEY=$AWS_ACCESS_KEY_ID"
              echo "REACT_APP_AWS_SECRET=$AWS_SECRET_ACCESS_KEY"
            } >> ./.env

            npm run build
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy Web App
          command: |
            chmod +x ./deploy-web.sh
            ./deploy-web.sh
  deploy-cron:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd cron-job && npm i
      - run:
          name: Build
          command: cd cron-job && npm run build
      - aws-cli/setup:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy Cron Job
          command: |
            chmod +x ./deploy-cron.sh
            ./deploy-cron.sh
workflows:
  deploy:
    jobs:
      - deploy-web:
          context:
            - AWS
            - TZEDAKAH_BOXES
          filters:
            branches:
              only:
                - main
      - deploy-cron:
          context: AWS
          filters:
            branches:
              only:
                - main