name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: cdt-fundraiser-test
          POSTGRES_PASSWORD: pwd
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun typecheck
      - run: bun e2e

  db:
    name: Database Update
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun drizzle
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
