name: Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

permissions:
  id-token: write

jobs:
  report:
    name: Send Out Daily Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun ./scripts/generate-and-send-report.ts
        env:
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
