on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  report:
    name: Send Out Daily Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.ACTIONS_IAM_ROLE }}
      - run: bun ./scripts/generate-and-send-report.ts
